#!/bin/bash

# Author: 	Marcos Dominguez <marcos@ampl.com>
#
# Description: 	Test script that creates pairs from an array of executables and
#		runs nl tests on them. These tests are from some book and website examples.
#		The file ./file_cmp_nl_X.sh where 'X = name of tests' will run the tests 
#		which consist of comparing the nl files generated by ampl and others.
#		If the nl files are identical (except of the first line) test will pass.
#		Activate -v for verbose mode.

set -e

EXIT_SUCCESS=0
EXIT_FAILURE=134

verbose_mode=false

# Parse arguments
while getopts v opts; do
   case ${opts} in
      v) verbose_mode=true ;;
      ?) echo "Usage: $0 [-v] EXEC1 EXEC2 ..."
      printf "\t -v: Verbose flag for nl tests.\n"
      printf "\t EXEC1 and EXEC2 are the AMPL executables which are being tested. Default: ampl and ax."
      exit $EXIT_SUCCESS ;;
   esac
done

# Change to tests directory (where .sh are)
tests_dir="../tests/"
cd $tests_dir

# TODO add "loop2", it doesn't work because of the demo license
# tests files (file_cmp_nl_X.sh)
test_array=("amplbook2" "logic" "loop1")
num_test=${#test_array[@]}

# executable files
exec_files="$@"
# if -v activated, verbose mode
if [ "$verbose_mode" = "true" ]; then
	exec_files="-v $exec_files"
fi

# Output status
stat=$EXIT_SUCCESS
failed_tests=0
ok_tests=0
# 1. Start testing
printf "\n### START TESTING NL FILES ###\n\n"
set +e
for (( t=0; t<$num_test; t++ ));
do
	echo "+ Running ${test_array[$t]} nl tests"
	# Run these tests located in the -d directory,
	./file_cmp_nl_${test_array[$t]}.sh -d basic_examples/${test_array[$t]} $exec_files
	# Failed or passed?
	if [[ $? -eq $EXIT_FAILURE ]]; then
		stat=$EXIT_FAILURE
		((failed_tests++))
	else 
		echo "${test_array[$t]} nl tests PASSED"		
		((ok_tests++))
	fi
	echo
done
set -e
printf "\n### END TESTING NL FILES ###\n\n"

# 2. Summary
if [[ $stat -eq $EXIT_SUCCESS ]]; then
    echo -e "ALL $ok_tests NL TESTS PASSED"
elif [[ $stat -eq $EXIT_FAILURE ]]; then
    echo -e "$failed_tests NL TESTS FAILED"
fi

exit $stat

