on:
  push:
    branches:
      - marcos_tests

name: New Getopts tests

jobs:
  run:
    name: ${{ matrix.config.os }} 
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-20.04}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Setup actions checkout
        uses: actions/checkout@v2
    
      - name: Install bash on MacOS
        if: runner.os == 'macOS'
        run: |
            brew install bash
            brew install gnu-sed 

      - name: Install dos2unix on Ubuntu
        if: runner.os == 'Linux'
        run: |
            sudo apt install dos2unix

      - name: Run tests
        run: |
            cd getopts/
            ./mygetopts.sh exec25 -fake --aa aarg exec1 -s -c c1 c2 -u -k
            ./mygetopts.sh exec25 --fake
            ./mygetopts.sh exec25 ----fake ---aa aarg exec1 --s -c c1 c2 c3fake -u -k -aa-: flag
            ./mygetopts.sh -a -a: -?/@! arg
            ./mygetopts.sh -c c1 -u -a arga -k
            ./mygetopts.sh -c -c -c -c -c
        shell: bash {0}
