on:
  push:
    branches:
      - main

name: Cross platform tests

jobs:
  run:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', md5: "md5sum"}
          - {os: macOS-latest, r: 'release', md5: "md5"}
          - {os: ubuntu-16.04, r: 'release', md5: "md5sum"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      MD5: ${{ matrix.config.md5 }}

    steps:
      - name: Setup actions checkout
        uses: actions/checkout@v2

      - name: Check for md5
        run: |
            cd ampl/test_scripts/
            $MD5 one.case
        shell: bash {0}
