on:
  push:
    branches:
      - main

name: Cross platform tests

jobs:
  run:
    name: ${{ matrix.config.os }} 
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-16.04}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Setup actions checkout
        uses: actions/checkout@v2
    
      - name: Install bash on MacOS
        if: runner.os == 'macOS'
        run: |
            brew install bash

      - name: Enable 32-bit on Ubuntu
        if: runner.os == 'Linux'
        run: | 
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y gcc-6-multilib

      - name: Run tests
        run: |
            cd bash/file
            ./build.sh
            ls -ltr build/bin
            file build/bin/main
        shell: bash {0}
