on:
  push:
    branches:
      - main

name: Cross platform tests

jobs:
  run:
    name: ${{ matrix.config.os }} 
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-20.04}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Setup actions checkout
        uses: actions/checkout@v2
    
        #      - name: Install bash on MacOS
        #        if: runner.os == 'macOS'
        #        run: |
        #            brew install bash
        #            brew install gnu-sed 
        #
        #      - name: Install dos2unix on Ubuntu
        #        if: runner.os == 'Linux'
        #        run: |
        #            sudo apt install dos2unix

      - name: Install AMPL
        run: |
            if [ "$RUNNER_OS" == 'Linux' ]; then
                ampl/baseline_scripts.sh linux-intel64
            elif [ "$RUNNER_OS" == 'Windows' ]; then
                ampl/baseline_scripts.sh mswin64
            elif [ "$RUNNER_OS" == 'macOS' ]; then 
                ampl/baseline_scripts.sh macos64
            else
                echo "$RUNNER_OS not supported"
                exit 1
            fi
      - name: Run tests
        run: |
            cd ampl/test_scripts
            ampl-baseline disappear.run
        shell: bash {0}
