on:
  push:
    branches:
      - main

name: Cross platform tests

jobs:
  run:
    name: ${{ matrix.config.os }} 
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-20.04}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Setup actions checkout
        uses: actions/checkout@v2
    
        #      - name: Install bash on MacOS
        #        if: runner.os == 'macOS'
        #        run: |
        #            brew install bash
        #            brew install gnu-sed 
        #
        #      - name: Install dos2unix on Ubuntu
        #        if: runner.os == 'Linux'
        #        run: |
        #            sudo apt install dos2unix
        #
      
      - name: Create dir
        run: |
            mkdir ampl
        shell: bash

      - name: Install AMPL (Linux)
        if: runner.os == 'Linux'
        run: |
            pwd
            ./scripts/prepare_baseline.sh linux-intel64
        shell: bash

      - name: Install AMPL (macOS)
        if: runner.os == 'macOS'
        run: |
            pwd
            ./scripts/prepare_baseline.sh macos64
        shell: bash

      - name: Install AMPL (Windows)
        if: runner.os == 'Windows'
        run: |
            pwd
            ./scripts/prepare_baseline.sh mswin64
        shell: bash

      - name: Run tests
        run: |
            pwd
            cd ampl_dir/test_scripts
            ampl-baseline disappear.run
        shell: bash
