on:
  push:
    branches:
      - main

name: Cross platform tests

jobs:
  run:
    name: ${{ matrix.config.os }} 
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-20.04}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Setup actions checkout
        uses: actions/checkout@v2
    
      - name: Install bash on MacOS
        if: runner.os == 'macOS'
        run: |
            brew install bash
            brew install gnu-sed 

      - name: Run tests
        run: |
            cd azure
            ./prep_xpl_tests.sh -d artifacts/ -v
            ./run_xpl_tests.sh -d artifacts/ -s 10000 -v
        shell: bash {0}
